#!/bin/sh
while(true)
do
#hwtemp=$(cat /sys/class/thermal/thermal_zone0/temp)
hwtemp=$(sudo vcgencmd measure_temp)
#hwtemp=$((hwtemp/1000))
echo $hwtemp
#substituido
#echo CPU Temperature $hwtemp ºc
cpufreq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)
cpufreq=$((cpufreq/1000))
echo CPU Frenquency $cpufreq MHZ
sleep 1
done
