#!/usr/bin/python
#coding: utf-8
print
import RPi.GPIO as GPIO
import time
import sys
import os
GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)
GPIO.setup(36, GPIO.OUT)
rele = 36

def ligar():
    GPIO.output(rele, GPIO.HIGH)

if __name__ == "__main__":
    ligar()
