#!/bin/sh
while(true)
do
limit=55
hwtemp=$(cat /sys/class/thermal/thermal_zone0/temp)
hwtemp=$((hwtemp/1000))
echo CPU Temperature $hwtemp ºC
cpufreq=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)
cpufreq=$((cpufreq/1000))
echo CPU Frenquency $cpufreq MHZ
if [     "$hwtemp" -ge "$limit" ]
then
         sudo shutdown -h now
fi
#else
sleep 30
done
